const fs = require('fs');

const baseKeys = {
  // Common
  home: { hi: "मुख्य पृष्ठ", en: "Home", mr: "मुख्य पृष्ठ", pa: "ਮੁੱਖ ਪੰਨਾ" },
  addLog: { hi: "काम लिखो", en: "Add Log", mr: "काम लिहा", pa: "ਕੰਮ ਲਿਖੋ" },
  expense: { hi: "खर्चा", en: "Expense", mr: "खर्च", pa: "ਖਰਚਾ" },
  summary: { hi: "सारांश", en: "Summary", mr: "सारांश", pa: "ਸਾਰਾਂਸ਼" },
  water: { hi: "पानी दिया", en: "Water Given", mr: "पाणी दिले", pa: "ਪਾਣੀ ਦਿੱਤਾ" },
  pesticide: { hi: "दवाई मारी", en: "Pesticide Applied", mr: "औषध मारले", pa: "ਦਵਾਈ ਮਾਰੀ" },
  seed: { hi: "बीज बोया", en: "Seeds Sown", mr: "बियाणे पेरले", pa: "ਬੀਜ ਬੋਏ" },
  workers: { hi: "मजदूर आए", en: "Workers Came", mr: "मजूर आले", pa: "ਮਜ਼ਦੂਰ ਆਏ" },
  addExpense: { hi: "खर्चा जोड़ो", en: "Add Expense", mr: "खर्च जोडा", pa: "ਖਰਚਾ ਜੋੜੋ" },
  totalExpense: { hi: "कुल खर्चा", en: "Total Expense", mr: "एकूण खर्च", pa: "ਕੁੱਲ ਖਰਚਾ" },
  totalIncome: { hi: "कुल कमाई", en: "Total Income", mr: "एकूण उत्पन्न", pa: "ਕੁੱਲ ਕਮਾਈ" },
  profit: { hi: "फायदा", en: "Profit", mr: "नफा", pa: "ਫਾਇਦਾ" },
  loss: { hi: "नुकसान", en: "Loss", mr: "नुकसान", pa: "ਨੁਕਸਾਨ" },
  save: { hi: "लिखो", en: "Save", mr: "जतन करा", pa: "ਲਿਖੋ" },
  season: { hi: "फसल", en: "Season", mr: "हंगाम", pa: "ਫ਼ਸਲ" },
  farm: { hi: "खेत", en: "Farm", mr: "शेत", pa: "ਖੇਤ" },
  other: { hi: "कुछ और", en: "Other", mr: "इतर", pa: "ਹੋਰ" },
  harvest: { hi: "कटाई", en: "Harvest", mr: "कापणी", pa: "ਵਾਢੀ" },
  login: { hi: "लॉगिन करें", en: "Login", mr: "लॉगिन", pa: "ਲੌਗਿਨ" },
  register: { hi: "रजिस्टर करें", en: "Register", mr: "नोंदणी", pa: "ਰਜਿਸਟਰ" },
  phone: { hi: "मोबाइल नंबर", en: "Mobile Number", mr: "मोबाईल नंबर", pa: "ਮੋਬਾਈਲ ਨੰਬਰ" },
  enterOtp: { hi: "OTP डालें", en: "Enter OTP", mr: "OTP टाका", pa: "OTP ਦਾਖਲ ਕਰੋ" },
  verifyOtp: { hi: "OTP जांचें", en: "Verify OTP", mr: "OTP तपासा", pa: "OTP ਜਾਂਚੋ" },
  sendOtp: { hi: "OTP भेजें", en: "Send OTP", mr: "OTP पाठवा", pa: "OTP ਭੇਜੋ" },
  name: { hi: "नाम", en: "Name", mr: "नाव", pa: "ਨਾਮ" },
  state: { hi: "राज्य", en: "State", mr: "राज्य", pa: "ਸੂਬਾ" },
  language: { hi: "भाषा", en: "Language", mr: "भाषा", pa: "ਭਾਸ਼ਾ" },
  farmName: { hi: "खेत का नाम", en: "Farm Name", mr: "शेताचे नाव", pa: "ਖੇਤ ਦਾ ਨਾਮ" },
  farmSize: { hi: "खेत का आकार (एकड़)", en: "Farm Size (Acres)", mr: "शेताचा आकार (एकर)", pa: "ਖੇਤ ਦਾ ਆਕਾਰ (ਏਕੜ)" },
  location: { hi: "गाँव/जिला", en: "Village/District", mr: "गाव/जिल्हा", pa: "ਪਿੰਡ/ਜ਼ਿਲਾ" },
  cropName: { hi: "फसल का नाम", en: "Crop Name", mr: "पिकाचे नाव", pa: "ਫ਼ਸਲ ਦਾ ਨਾਮ" },
  startDate: { hi: "शुरुआत की तारीख", en: "Start Date", mr: "सुरुवात तारीख", pa: "ਸ਼ੁਰੂਆਤ ਦੀ ਤਾਰੀਖ" },
  endDate: { hi: "खत्म होने की तारीख", en: "End Date", mr: "शेवट तारीख", pa: "ਖਤਮ ਹੋਣ ਦੀ ਤਾਰੀਖ" },
  addFarm: { hi: "खेत जोड़ें", en: "Add Farm", mr: "शेत जोडा", pa: "ਖੇਤ ਜੋੜੋ" },
  addSeason: { hi: "फसल शुरू करें", en: "Start Season", mr: "हंगाम सुरू करा", pa: "ਫ਼ਸਲ ਸ਼ੁਰੂ ਕਰੋ" },
  logActivity: { hi: "काम नोट करें", en: "Log Activity", mr: "काम नोंदवा", pa: "ਕੰਮ ਨੋਟ ਕਰੋ" },
  activityType: { hi: "काम का प्रकार", en: "Activity Type", mr: "कामाचा प्रकार", pa: "ਕੰਮ ਦੀ ਕਿਸਮ" },
  note: { hi: "नोट", en: "Note", mr: "नोट", pa: "ਨੋਟ" },
  date: { hi: "तारीख", en: "Date", mr: "तारीख", pa: "ਤਾਰੀਖ" },
  workerCount: { hi: "मजदूरों की संख्या", en: "Number of Workers", mr: "मजुरांची संख्या", pa: "ਮਜ਼ਦੂਰਾਂ ਦੀ ਗਿਣਤੀ" },
  amount: { hi: "रकम", en: "Amount", mr: "रक्कम", pa: "ਰਕਮ" },
  category: { hi: "वर्ग", en: "Category", mr: "श्रेणी", pa: "ਸ਼੍ਰੇਣੀ" },
  description: { hi: "विवरण", en: "Description", mr: "वर्णन", pa: "ਵੇਰਵਾ" },
  quantity: { hi: "मात्रा", en: "Quantity", mr: "प्रमाण", pa: "ਮਾਤਰਾ" },
  unit: { hi: "इकाई", en: "Unit", mr: "एकक", pa: "ਇਕਾਈ" },
  pricePerUnit: { hi: "प्रति इकाई कीमत", en: "Price Per Unit", mr: "प्रति एकक किंमत", pa: "ਪ੍ਰਤੀ ਇਕਾਈ ਕੀਮਤ" },
  buyerName: { hi: "खरीदार का नाम", en: "Buyer Name", mr: "खरेदीदाराचे नाव", pa: "ਖਰੀਦਦਾਰ ਦਾ ਨਾਮ" },
  totalProfit: { hi: "कुल फायदा", en: "Total Profit", mr: "एकूण नफा", pa: "ਕੁੱਲ ਫਾਇਦਾ" },
  totalLoss: { hi: "कुल नुकसान", en: "Total Loss", mr: "एकूण नुकसान", pa: "ਕੁੱਲ ਨੁਕਸਾਨ" },
  workingDays: { hi: "काम के दिन", en: "Working Days", mr: "कामाचे दिवस", pa: "ਕੰਮ ਦੇ ਦਿਨ" },
  report: { hi: "रिपोर्ट", en: "Report", mr: "अहवाल", pa: "ਰਿਪੋਰਟ" },
  loading: { hi: "लोड हो रहा है...", en: "Loading...", mr: "लोड होत आहे...", pa: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ..." },
  error: { hi: "कुछ गलत हुआ", en: "Something went wrong", mr: "काही चुकले", pa: "ਕੁਝ ਗਲਤ ਹੋਇਆ" },
  success: { hi: "सफल", en: "Success", mr: "यशस्वी", pa: "ਸਫਲ" },
  delete: { hi: "हटाएं", en: "Delete", mr: "हटवा", pa: "ਮਿਟਾਓ" },
  edit: { hi: "संपादित करें", en: "Edit", mr: "संपादित करा", pa: "ਸੰਪਾਦਿਤ ਕਰੋ" },
  cancel: { hi: "रद्द करें", en: "Cancel", mr: "रद्द करा", pa: "ਰੱਦ ਕਰੋ" },
  confirm: { hi: "पक्का करें", en: "Confirm", mr: "पुष्टी करा", pa: "ਪੱਕਾ ਕਰੋ" },
  namaste: { hi: "नमस्ते", en: "Namaste", mr: "नमस्कार", pa: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ" },
  todayWork: { hi: "आज का काम", en: "Today's Work", mr: "आजचे काम", pa: "ਅੱਜ ਦਾ ਕੰਮ" },
  activeSeasons: { hi: "चालू फसलें", en: "Active Seasons", mr: "सक्रिय हंगाम", pa: "ਚਾਲੂ ਫ਼ਸਲਾਂ" },
  noData: { hi: "कोई डेटा नहीं", en: "No Data", mr: "डेटा नाही", pa: "ਕੋਈ ਡੇਟਾ ਨਹੀਂ" },
  myFarms: { hi: "मेरे खेत", en: "My Farms", mr: "माझे शेत", pa: "ਮੇਰੇ ਖੇਤ" },
  settings: { hi: "सेटिंग", en: "Settings", mr: "सेटिंग्ज", pa: "ਸੈਟਿੰਗਾਂ" },
  khata: { hi: "खाता", en: "Khata", mr: "खाते", pa: "ਖਾਤਾ" },
  addIncome: { hi: "आमदनी जोड़ें", en: "Add Income", mr: "उत्पन्न जोडा", pa: "ਕਮਾਈ ਜੋੜੋ" },
  netBalance: { hi: "शुद्ध बचत", en: "Net Balance", mr: "निव्वळ शिल्लक", pa: "ਸ਼ੁੱਧ ਬਚਤ" },
  reports: { hi: "रिपोर्ट्स", en: "Reports", mr: "अहवाल", pa: "ਰਿਪੋਰਟਾਂ" },
  inventory: { hi: "भंडार", en: "Inventory", mr: "भांडार", pa: "ਭੰਡਾਰ" },
  borrowings: { hi: "उधार", en: "Borrowings", mr: "उधार", pa: "ਉਧਾਰ" },
  market: { hi: "मंडी", en: "Market", mr: "मंडी", pa: "ਮੰਡੀ" },
  credit: { hi: "ऋण", en: "Credit", mr: "कर्ज", pa: "ਕਰਜ਼ਾ" },

  // Dashboard keys
  quickActions: { hi: "⚡ जल्दी लिखें", en: "⚡ Quick Log", mr: "⚡ जलद लिहा", pa: "⚡ ਜਲਦੀ ਲਿਖੋ" },
  recentActivity: { hi: "📋 आज की गतिविधि", en: "📋 Today's Activity", mr: "📋 आजची कृती", pa: "📋 ਅੱਜ ਦੀ ਗਤੀਵਿਧੀ" },
  viewAll: { hi: "सभी देखें", en: "View All", mr: "सर्व पहा", pa: "ਸਾਰੇ ਦੇਖੋ" },
  addFarmPrompt: { hi: "पहले खेत जोड़ें", en: "Add Farm First", mr: "प्रथम शेत जोडा", pa: "ਪਹਿਲਾਂ ਖੇਤ ਜੋੜੋ" },
  addFarmDesc: { hi: "अपनी खेती की शुरुआत करने के लिए अपना पहला खेत जोड़ें", en: "Add your first farm to start managing your agriculture", mr: "शेतीची सुरुवात करण्यासाठी आपले पहिले शेत जोडा", pa: "ਖੇਤੀ ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣਾ ਪਹਿਲਾ ਖੇਤ ਜੋੜੋ" },
  noActiveSeason: { hi: "कोई फसल चालू नहीं है", en: "No Active Season", mr: "कोणताही हंगाम सक्रिय नाही", pa: "ਕੋਈ ਫ਼ਸਲ ਚਾਲੂ ਨਹੀਂ ਹੈ" },
  activeSeasonLabel: { hi: "चालू फसल", en: "Active Season", mr: "सक्रिय हंगाम", pa: "ਚਾਲੂ ਫ਼ਸਲ" },
  startedOn: { hi: "शुरू:", en: "Started:", mr: "सुरू:", pa: "ਸ਼ੁਰੂ:" },
  days: { hi: "दिन", en: "days", mr: "दिवस", pa: "ਦਿਨ" },
  acre: { hi: "एकड़", en: "acres", mr: "एकर", pa: "ਏਕੜ" },
  completedTasks: { hi: "काम पूरे किए", en: "tasks done", mr: "कामे पूर्ण झाली", pa: "ਕੰਮ ਪੂਰੇ ਕੀਤੇ" },
  nothingYet: { hi: "अभी तक कुछ नहीं", en: "Nothing yet", mr: "अद्याप काहीही नाही", pa: "ਹਾਲੇ ਕੁਝ ਨਹੀਂ" },
  
  // Home Page Added Keys
  phaseSowing: { hi: "बुवाई", en: "Sowing", mr: "पेरणी", pa: "ਬਿਜਾਈ" },
  phaseSprouting: { hi: "अंकुरण", en: "Sprouting", mr: "अंकुरण", pa: "ਪੁੰਗਰਨਾ" },
  phaseGrowing: { hi: "बढ़वार", en: "Growing", mr: "वाढ", pa: "ਵਾਧਾ" },
  phaseFlowering: { hi: "फूल आना", en: "Flowering", mr: "फुले येणे", pa: "ਫੁੱਲ ਆਉਣਾ" },
  phaseRipening: { hi: "पकाव", en: "Ripening", mr: "पक्वता", pa: "ਪੱਕਣਾ" },
  phaseHarvestReady: { hi: "कटाई", en: "Harvest Ready", mr: "कापणी", pa: "ਵਾਢੀ ਲਈ ਤਿਆਰ" },
  advSowing: { hi: "मिट्टी की नमी जांचें। समान अंकुरण सुनिश्चित करें।", en: "Check soil moisture. Ensure even germination.", mr: "मातीची आर्द्रता तपासा. समान अंकुरण सुनिश्चित करा.", pa: "ਮਿੱਟੀ ਦੀ ਨਮੀ ਦੀ ਜਾਂਚ ਕਰੋ। ਬਰਾਬਰ ਪੁੰਗਰਨਾ ਯਕੀਨੀ ਬਣਾਓ।" },
  advSprouting: { hi: "पहली सिंचाई का समय। जड़ खाद डालें।", en: "First watering due. Apply basal fertilizer.", mr: "पहिली सिंचनाची वेळ. बेसल खत घाला.", pa: "ਪਹਿਲੀ ਸਿੰਚਾਈ ਦਾ ਸਮਾਂ। ਬੇਸਲ ਖਾਦ ਪਾਓ।" },
  advGrowing: { hi: "निराई-गुड़ाई करें। कीड़े-मकोड़ों पर नज़र रखें।", en: "Weeding recommended. Monitor for pests.", mr: "तण काढण्याची शिफारस. कीटकांवर लक्ष ठेवा.", pa: "ਨਦੀਨ ਕੱਢਣ ਦੀ ਸਿਫਾਰਸ਼। ਕੀੜਿਆਂ 'ਤੇ ਨਜ਼ਰ ਰੱਖੋ।" },
  advFlowering: { hi: "फूल आने की अवस्था — सिंचाई कम करें। दवाई न डालें।", en: "Flowering stage — reduce irrigation. No sprays.", mr: "फुलांची अवस्था — सिंचन कमी करा. फवारणी टाळा.", pa: "ਫੁੱਲ ਆਉਣ ਦੀ ਅਵਸਥਾ — ਸਿੰਚਾਈ ਘਟਾਓ। ਕੋਈ ਸਪਰੇਅ ਨਹੀਂ।" },
  advRipening: { hi: "कटाई से 2 हफ्ते पहले सिंचाई बंद करें।", en: "Stop irrigation 2 weeks before harvest.", mr: "कापणीपूर्वी 2 आठवडे सिंचन थांबवा.", pa: "ਵਾਢੀ ਤੋਂ 2 ਹਫ਼ਤੇ ਪਹਿਲਾਂ ਸਿੰਚਾਈ ਬੰਦ ਕਰੋ।" },
  advHarvestReady: { hi: "फसल कटाई के लिए तैयार है। व्यापारी से संपर्क करें।", en: "Crop is ready for harvest. Contact your trader.", mr: "पीक कापणीसाठी तयार आहे. व्यापार्‍याशी संपर्क साधा.", pa: "ਫ਼ਸਲ ਵਾਢੀ ਲਈ ਤਿਆਰ ਹੈ। ਵਪਾਰੀ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।" },
  farmer: { hi: "किसान", en: "Farmer", mr: "शेतकरी", pa: "ਕਿਸਾਨ" },
  dayStreak: { hi: "दिन", en: "day streak", mr: "दिवस", pa: "ਦਿਨ" },
  incomeLabel: { hi: "आमदनी", en: "Income", mr: "उत्पन्न", pa: "ਕਮਾਈ" },
  expenseLabel: { hi: "खर्च", en: "Expense", mr: "खर्च", pa: "ਖਰਚਾ" },
  net: { hi: "बचत", en: "Net", mr: "शिल्लक", pa: "ਬਚਤ" },
  todaysAdvisory: { hi: "आज का सुझाव", en: "Today's Advisory", mr: "आजचा सल्ला", pa: "ਅੱਜ ਦਾ ਸੁਝਾਅ" },
  mandi: { hi: "मंडी", en: "MANDI", mr: "मंडी", pa: "ਮੰਡੀ" },
  quickLog: { hi: "जल्दी लिखें", en: "Quick Log", mr: "जलद नोंदवा", pa: "ਜਲਦੀ ਲਿਖੋ" },
  noFarmsYet: { hi: "अभी कोई खेत नहीं", en: "No Farms Yet", mr: "अद्याप शेत नाही", pa: "ਹਾਲੇ ਕੋਈ ਖੇਤ ਨਹੀਂ" },
  addFirstFarm: { hi: "अपना पहला खेत जोड़ें और खेती का हिसाब शुरू करें।", en: "Add your first farm to start tracking your crops, expenses, and harvests.", mr: "पहिले शेत जोडा आणि शेतीचा हिशेब सुरू करा.", pa: "ਆਪਣਾ ਪਹਿਲਾ ਖੇਤ ਜੋੜੋ ਅਤੇ ਖੇਤੀ ਦਾ ਹਿਸਾਬ ਸ਼ੁਰੂ ਕਰੋ।" },
  voiceRecord: { hi: "बोल कर लिखें", en: "Voice Record", mr: "आवाज नोंदवा", pa: "ਬੋਲ ਕੇ ਲਿਖੋ" },
  voiceMicPrompt: { hi: "हरे बटन को दबाएं और बोलें।", en: "Press the green mic and speak.", mr: "हिरवे बटण दाबा आणि बोला.", pa: "ਹਰਾ ਬਟਨ ਦਬਾਓ ਅਤੇ ਬੋਲੋ।" },
  voiceTrySaying: { hi: "बोल कर देखें", en: "Try saying", mr: "बोलून पहा", pa: "ਬੋਲ ਕੇ ਦੇਖੋ" },
  voiceExample: { hi: "मैंने 500 रुपये खाद पर खर्च किए", en: "I spent ₹500 on fertilizer", mr: "मी खतावर ५०० रुपये खर्च केले", pa: "ਮੈਂ 500 ਰੁਪਏ ਖਾਦ 'ਤੇ ਖਰਚੇ" },
  viewProfitability: { hi: "फसल की कमाई देखें (P&L)", en: "View Crop Profitability (P&L)", mr: "पिकाचा नफा पहा (P&L)", pa: "ਫ਼ਸਲ ਦੀ ਕਮਾਈ ਦੇਖੋ (P&L)" },
  liveUpdate: { hi: "लाइव अपडेट", en: "Live Update", mr: "थेट अपडेट", pa: "ਲਾਈਵ ਅਪਡੇਟ" },
  upcomingActivities: { hi: "आगामी कार्य", en: "Upcoming Activities", mr: "आगामी कामे", pa: "ਆਉਣ ਵਾਲੇ ਕੰਮ" },
  today: { hi: "आज", en: "Today", mr: "आज", pa: "ਅੱਜ" },
  lateDays: { hi: "दिन देर", en: "Late", mr: "दिवस उशीर", pa: "ਦਿਨ ਦੇਰੀ" },
  inDays: { hi: "दिन में", en: "In", mr: "दिवसात", pa: "ਦਿਨਾਂ ਵਿੱਚ" },
  markDone: { hi: "पूरा किया", en: "Mark Done", mr: "पूर्ण केले", pa: "ਪੂਰਾ ਕੀਤਾ" },
  lowInventory: { hi: "स्टॉक कम", en: "Low Inventory", mr: "स्टॉक कमी", pa: "ਸਟਾਕ ਘੱਟ" },
  unknownActivity: { hi: "अज्ञात गतिविधि", en: "Unknown Activity", mr: "अज्ञात कृती", pa: "ਅਗਿਆਤ ਗਤੀਵਿਧੀ" },
  workersCount: { hi: "मजदूर", en: "workers", mr: "मजूर", pa: "ਮਜ਼ਦੂਰ" },
  farmersWisdom: { hi: "किसान की बात", en: "Farmer's Wisdom", mr: "शेतकऱ्याचे शहाणपण", pa: "ਕਿਸਾਨ ਦੀ ਗੱਲ" },
  amountRs: { hi: "रकम (₹)", en: "Amount (₹)", mr: "रक्कम (₹)", pa: "ਰਕਮ (₹)" },
  optional: { hi: "वैकल्पिक", en: "Optional", mr: "वैकल्पिक", pa: "ਵਿਕਲਪਿਕ" },
  eg500: { hi: "जैसे 500", en: "e.g. 500", mr: "उदा. ५००", pa: "ਜਿਵੇਂ 500" },
  eg5: { hi: "जैसे 5", en: "e.g. 5", mr: "उदा. ५", pa: "ਜਿਵੇਂ 5" },
  optionalNote: { hi: "नोट (वैकल्पिक)", en: "Optional note...", mr: "नोट (वैकल्पिक)", pa: "ਨੋਟ (ਵਿਕਲਪਿਕ)" },
  greetingNight: { hi: "शुभ रात्रि", en: "Good Night", mr: "शुभ रात्री", pa: "ਸ਼ੁਭ ਰਾਤ" },
  greetingMorning: { hi: "सुप्रभात", en: "Good Morning", mr: "सुप्रभात", pa: "ਸ਼ੁਭ ਸਵੇਰ" },
  greetingAfternoon: { hi: "नमस्ते", en: "Good Afternoon", mr: "नमस्कार", pa: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ" },
  greetingEvening: { hi: "शुभ संध्या", en: "Good Evening", mr: "शुभ संध्या", pa: "ਸ਼ੁਭ ਸ਼ਾਮ" },


  gettingMandiPrices: { hi: "मंडी के भाव मिल रहे हैं...", en: "Getting Mandi Prices...", mr: "मंडीचे भाव मिळत आहेत...", pa: "ਮੰਡੀ ਦੇ ਭਾਅ ਮਿਲ ਰਹੇ ਹਨ..." },
  fetchingMandiData: { hi: "आपके स्थानीय बाजारों के लिए लाइव डेटा प्राप्त किया जा रहा है।", en: "Fetching live data for your local markets.", mr: "तुमच्या स्थानिक बाजारांसाठी थेट डेटा मिळवत आहे.", pa: "ਤੁਹਾਡੇ ਸਥਾਨਕ ਬਾਜ਼ਾਰਾਂ ਲਈ ਲਾਈਵ ਡੇਟਾ ਪ੍ਰਾਪਤ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ।" },
  mandiLive: { hi: "मंडी लाइव", en: "Mandi Live", mr: "मंडी लाईव्ह", pa: "ਮੰਡੀ ਲਾਈਵ" },
  yourLocalMarket: { hi: "आपकी स्थानीय मंडी", en: "Your Local Market", mr: "तुमची स्थानिक मंडी", pa: "ਤੁਹਾਡੀ ਸਥਾਨਕ ਮੰਡੀ" },
  searchCropPlaceholder: { hi: "फसल खोजें (जैसे: गेहूं, प्याज)...", en: "Search crop (e.g. Wheat, Onion)...", mr: "पीक शोधा (उदा. गहू, कांदा)...", pa: "ਫ਼ਸਲ ਲੱਭੋ (ਜਿਵੇਂ: ਕਣਕ, ਪਿਆਜ਼)..." },
  mandiAdviceLabel: { hi: "मंडी सलाह", en: "Mandi Advice (मंडी सलाह)", mr: "मंडी सल्ला", pa: "ਮੰਡੀ ਸਲਾਹ" },
  todaysPrices: { hi: "आज के भाव", en: "Today's Prices", mr: "आजचे भाव", pa: "ਅੱਜ ਦੇ ਭਾਅ" },
  rsPerQuintal: { hi: "₹ प्रति क्विंटल", en: "₹ per Quintal", mr: "₹ प्रति क्विंटल", pa: "₹ ਪ੍ਰਤੀ ਕੁਇੰਟਲ" },
  advicePrefix: { hi: "सलाह:", en: "Advice:", mr: "सल्ला:", pa: "ਸਲਾਹ:" },
  sevenDayTrend: { hi: "7 दिन का रुझान", en: "7-Day Trend", mr: "७ दिवसांचा कल", pa: "7 ਦਿਨਾਂ ਦਾ ਰੁਝਾਨ" },
  noCropsFound: { hi: "कोई फसल नहीं मिली", en: "No crops found matching", mr: "कोणतेही पीक आढळले नाही", pa: "ਕੋਈ ਫ਼ਸਲ ਨਹੀਂ ਮਿਲੀ" },

  // Settings & Farms
  egFarmName: { hi: "जैसे: घर वाला खेत", en: "e.g. Home Farm", mr: "उदा. घराजवळील शेत", pa: "ਜਿਵੇਂ: ਘਰ ਵਾਲਾ ਖੇਤ" },
  areaUnitStar: { hi: "क्षेत्रफल ({unitLabel}) *", en: "Area ({unitLabel}) *", mr: "क्षेत्रफळ ({unitLabel}) *", pa: "ਖੇਤਰਫਲ ({unitLabel}) *" },
  eg5Acre: { hi: "जैसे: 5", en: "e.g. 5", mr: "उदा. ५", pa: "ਜਿਵੇਂ: 5" },
  villageDistrictStar: { hi: "गाँव / जिला *", en: "Village / District *", mr: "गाव / जिल्हा *", pa: "ਪਿੰਡ / ਜ਼ਿਲਾ *" },
  speakOrType: { hi: "बोलें या टाइप करें...", en: "Speak or type...", mr: "बोला किंवा टाईप करा...", pa: "ਬੋਲੋ ਜਾਂ ਟਾਈਪ ਕਰੋ..." },
  additionalInfoOptional: { hi: "अतिरिक्त जानकारी (वैकल्पिक)", en: "Additional Info (Optional)", mr: "अतिरिक्त माहिती (वैकल्पिक)", pa: "ਵਾਧੂ ਜਾਣਕਾਰੀ (ਵਿਕਲਪਿਕ)" },
  landType: { hi: "भूमि का प्रकार", en: "Land Type", mr: "जमिनीचा प्रकार", pa: "ਜ਼ਮੀਨ ਦੀ ਕਿਸਮ" },
  selectOption: { hi: "चुनें...", en: "Select...", mr: "निवडा...", pa: "ਚੁਣੋ..." },
  irrigationSource: { hi: "सिंचाई का स्रोत", en: "Irrigation Source", mr: "सिंचनाचे स्त्रोत", pa: "ਸਿੰਚਾਈ ਦਾ ਸਰੋਤ" },
  soilType: { hi: "मिट्टी का प्रकार", en: "Soil Type", mr: "मातीचा प्रकार", pa: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ" },
  farmNameLabel: { hi: "खेत का नाम", en: "Farm Name", mr: "शेताचे नाव", pa: "ਖੇਤ ਦਾ ਨਾਮ" },
  areaUnit: { hi: "क्षेत्रफल ({unitLabel})", en: "Area ({unitLabel})", mr: "क्षेत्रफळ ({unitLabel})", pa: "ਖੇਤਰਫਲ ({unitLabel})" },
  villageDistrict: { hi: "गाँव / जिला", en: "Village / District", mr: "गाव / जिल्हा", pa: "ਪਿੰਡ / ਜ਼ਿਲਾ" },
  newSeasonIn: { hi: "में नई फसल", en: "New season in", mr: "मध्ये नवीन हंगाम", pa: "ਵਿੱਚ ਨਵੀਂ ਫ਼ਸਲ" },
  cropNameStar: { hi: "फसल का नाम *", en: "Crop Name *", mr: "पिकाचे नाव *", pa: "ਫ਼ਸਲ ਦਾ ਨਾਮ *" },
  speakOrTypeCrop: { hi: "फसल का नाम बोलें या लिखें...", en: "Speak or type crop name...", mr: "पिकाचे नाव बोला किंवा लिहा...", pa: "ਫ਼ਸਲ ਦਾ ਨਾਮ ਬੋਲੋ ਜਾਂ ਲਿਖੋ..." },
  sowingDateStar: { hi: "बुवाई की तारीख *", en: "Sowing Date *", mr: "पेरणीची तारीख *", pa: "ਬਿਜਾਈ ਦੀ ਤਾਰੀਖ *" },
  deleteFarmWarning: { hi: "और उससे जुड़ा सारा डेटा (फसलें, खर्चे, आमदनी) हमेशा के लिए मिट जाएगा।", en: "and all its associated data (seasons, expenses, income) will be permanently deleted.", mr: "आणि त्यासंबंधित सर्व डेटा (हंगाम, खर्च, उत्पन्न) कायमचे हटवले जातील.", pa: "ਅਤੇ ਇਸ ਨਾਲ ਜੁੜਿਆ ਸਾਰਾ ਡੇਟਾ (ਫ਼ਸਲਾਂ, ਖਰਚੇ, ਕਮਾਈ) ਹਮੇਸ਼ਾ ਲਈ ਮਿਟ ਜਾਵੇਗਾ।" },
  yesDelete: { hi: "हाँ, हटाएं", en: "Yes, Delete", mr: "होय, हटवा", pa: "ਹਾਂ, ਮਿਟਾਓ" },
  completeSeasonWarning: { hi: "की फसल को पूर्ण मार्क करेंगे। बाद में नई फसल शुरू कर सकते हैं।", en: "season will be marked complete. You can start a new season later.", mr: "हंगाम पूर्ण म्हणून चिन्हांकित केले जाईल. तुम्ही नंतर नवीन हंगाम सुरू करू शकता.", pa: "ਦੀ ਫ਼ਸਲ ਨੂੰ ਪੂਰਾ ਮਾਰਕ ਕਰੇਗਾ। ਬਾਅਦ ਵਿੱਚ ਨਵੀਂ ਫ਼ਸਲ ਸ਼ੁਰੂ ਕਰ ਸਕਦੇ ਹੋ।" },
  yesComplete: { hi: "हाँ, पूरी करें", en: "Yes, Complete", mr: "होय, पूर्ण करा", pa: "ਹਾਂ, ਪੂਰਾ ਕਰੋ" },
  kisanTrustScore: { hi: "किसान ट्रस्ट स्कोर", en: "Kisan Trust Score", mr: "किसान ट्रस्ट स्कोर", pa: "ਕਿਸਾਨ ਟਰੱਸਟ ਸਕੋਰ" },
  languageSettings: { hi: "भाषा / Language", en: "Language", mr: "भाषा", pa: "ਭਾਸ਼ਾ" },
  changeAppLanguage: { hi: "ऐप की भाषा बदलें", en: "Change app language", mr: "अॅपची भाषा बदला", pa: "ਐਪ ਦੀ ਭਾਸ਼ਾ ਬਦਲੋ" },
  landUnitSettings: { hi: "ज़मीन की इकाई / Land Unit", en: "Land Unit", mr: "जमिनीचे एकक", pa: "ਜ਼ਮੀਨ ਦੀ ਇਕਾਈ" },
  chooseAcreBigha: { hi: "एकड़, बीघा या हेक्टेयर चुनें", en: "Choose Acre, Bigha or Hectare", mr: "एकर, बिघा किंवा हेक्टर निवडा", pa: "ਏਕੜ, ਬਿੱਘਾ ਜਾਂ ਹੈਕਟੇਅਰ ਚੁਣੋ" },
  changePin: { hi: "PIN बदलें", en: "Change PIN", mr: "PIN बदला", pa: "PIN ਬਦਲੋ" },
  updateLoginPin: { hi: "अपना लॉगिन PIN अपडेट करें", en: "Update your login PIN", mr: "तुमचा लॉगिन PIN अपडेट करा", pa: "ਆਪਣਾ ਲੌਗਿਨ PIN ਅਪਡੇਟ ਕਰੋ" },
  dataSecurity: { hi: "डेटा सुरक्षा", en: "Data Security", mr: "डेटा सुरक्षा", pa: "ਡੇਟਾ ਸੁਰੱਖਿਆ" },
  setNewPinInstruction: { hi: "4–6 अंकों का नया PIN सेट करें", en: "Set a new 4-6 digit PIN", mr: "४-६ अंकी नवीन PIN सेट करा", pa: "4-6 ਅੰਕਾਂ ਦਾ ਨਵਾਂ PIN ਸੈੱਟ ਕਰੋ" },
  pinChangedSuccess: { hi: "PIN सफलतापूर्वक बदल गया!", en: "PIN successfully changed!", mr: "PIN यशस्वीरित्या बदलला!", pa: "PIN ਸਫਲਤਾਪੂਰਵਕ ਬਦਲ ਗਿਆ!" },
  currentPinLabel: { hi: "मौजूदा PIN", en: "Current PIN", mr: "सध्याचा PIN", pa: "ਮੌਜੂਦਾ PIN" },
  currentPinPlaceholder: { hi: "मौजूदा PIN डालें", en: "Enter current PIN", mr: "सध्याचा PIN टाका", pa: "ਮੌਜੂਦਾ PIN ਦਾਖਲ ਕਰੋ" },
  newPinLabel: { hi: "नया PIN", en: "New PIN", mr: "नवीन PIN", pa: "ਨਵਾਂ PIN" },
  newPinPlaceholder: { hi: "4–6 अंकों का PIN", en: "4-6 digit PIN", mr: "४-६ अंकी PIN", pa: "4-6 ਅੰਕਾਂ ਦਾ PIN" },
  confirmPinLabel: { hi: "PIN दोबारा लिखें", en: "Confirm PIN", mr: "PIN पुन्हा लिहा", pa: "PIN ਦੁਬਾਰਾ ਲਿਖੋ" },
  confirmPinPlaceholder: { hi: "नया PIN फिर लिखें", en: "Re-enter new PIN", mr: "नवीन PIN पुन्हा लिहा", pa: "ਨਵਾਂ PIN ਫਿਰ ਲਿਖੋ" },
  loginToViewSettings: { hi: "सेटिंग्स देखने के लिए लॉगिन करें।", en: "Login to view settings.", mr: "सेटिंग्ज पाहण्यासाठी लॉगिन करा.", pa: "ਸੈਟਿੰਗਾਂ ਦੇਖਣ ਲਈ ਲੌਗਿਨ ਕਰੋ।" },
  accountAndPreferences: { hi: "खाता और प्राथमिकताएं", en: "Account and Preferences", mr: "खाते आणि प्राधान्ये", pa: "ਖਾਤਾ ਅਤੇ ਤਰਜੀਹਾਂ" },
  kisanScoreSection: { hi: "किसान स्कोर (Kisan Score)", en: "Kisan Score", mr: "किसान स्कोर", pa: "ਕਿਸਾਨ ਸਕੋਰ" },
  myFarmsSection: { hi: "मेरे खेत (My Farms)", en: "My Farms", mr: "माझे शेत", pa: "ਮੇਰੇ ਖੇਤ" },
  notificationsSection: { hi: "सूचनाएं (Notifications)", en: "Notifications", mr: "सूचना", pa: "ਸੂਚਨਾਵਾਂ" },
  languageAndUnitSection: { hi: "भाषा और इकाई (Language & Units)", en: "Language & Units", mr: "भाषा आणि एकके", pa: "ਭਾਸ਼ਾ ਅਤੇ ਇਕਾਈ" },
  securitySection: { hi: "खाता सुरक्षा (Security)", en: "Security", mr: "सुरक्षा", pa: "ਸੁਰੱਖਿਆ" },
  helpSection: { hi: "सहायता (Help & Info)", en: "Help & Info", mr: "मदत आणि माहिती", pa: "ਮਦਦ ਅਤੇ ਜਾਣਕਾਰੀ" },
  appVersion: { hi: "संस्करण 1.0.0 · Enterprise Edition", en: "Version 1.0.0 · Enterprise Edition", mr: "आवृत्ती १.०.० · एंटरप्राइज संस्करण", pa: "ਸੰਸਕਰਣ 1.0.0 · ਐਂਟਰਪ੍ਰਾਈਜ਼ ਐਡੀਸ਼ਨ" },

  // Khata & Credit
  startKhataPrompt: { hi: "अपना पहला खर्च या आमदनी दर्ज करके अपना बहीखाता शुरू करें।", en: "Start your Khata by recording your first income or expense.", mr: "तुमचा पहिला खर्च किंवा उत्पन्न नोंदवून खाते सुरू करा.", pa: "ਆਪਣਾ ਪਹਿਲਾ ਖਰਚਾ ਜਾਂ ਕਮਾਈ ਦਰਜ ਕਰਕੇ ਆਪਣਾ ਖਾਤਾ ਸ਼ੁਰੂ ਕਰੋ।" },
  balancePrefix: { hi: "शेष:", en: "Bal:", mr: "शिल्लक:", pa: "ਬਾਕੀ:" },
  initScoring: { hi: "स्कोरिंग इंजन लोड हो रहा है", en: "Initializing Scoring Engine", mr: "स्कोरिंग इंजिन लोड होत आहे", pa: "ਸਕੋਰਿੰਗ ਇੰਜਣ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ" },
  govtSchemeLabel: { hi: "सरकारी योजना पात्रता", en: "Govt. Scheme Eligibility", mr: "सरकारी योजना पात्रता", pa: "ਸਰਕਾਰੀ ਯੋਜਨਾ ਯੋਗਤਾ" },
  maxScore850: { hi: "अधिकतम 850", en: "Max 850", mr: "कमाल 850", pa: "ਵੱਧ ਤੋਂ ਵੱਧ 850" },
  tierLabelStr: { hi: "स्तर", en: "Tier", mr: "स्तर", pa: "ਪੱਧਰ" },
  baseProfile: { hi: "मूल प्रोफाइल", en: "Base Profile", mr: "मूळ प्रोफाइल", pa: "ਮੂਲ ਪ੍ਰੋਫਾਈਲ" },
  identityVerified: { hi: "पहचान सत्यापित।", en: "Identity verified.", mr: "ओळख सत्यापित.", pa: "ਪਛਾਣ ਤਸਦੀਕ।" },
  khataActivity: { hi: "खाता गतिविधि", en: "Khata Activity", mr: "खाते कृती", pa: "ਖਾਤਾ ਗਤੀਵਿਧੀ" },
  consistentEntries: { hi: "लगातार दैनिक प्रविष्टियाँ।", en: "Consistent daily entries.", mr: "सातत्यपूर्ण दररोजच्या नोंदी.", pa: "ਲਗਾਤਾਰ ਰੋਜ਼ਾਨਾ ਐਂਟਰੀਆਂ।" },
  creditReliability: { hi: "ऋण विश्वसनीयता", en: "Credit Reliability", mr: "कर्ज विश्वासार्हता", pa: "ਕਰਜ਼ਾ ਭਰੋਸੇਯੋਗਤਾ" },
  creditAdvisoryText: { hi: "750 से ऊपर स्कोर वाले किसानों की सब्सिडी जल्दी पास होती है। और योजनाएं खोलने के लिए रोज़ का हिसाब रखें!", en: "Farmers with a Readiness Score above 750 get their subsidy paperwork approved 3x faster. Keep logging your daily Khata to unlock the best schemes!", mr: "750 पेक्षा जास्त स्कोअर असलेल्या शेतकऱ्यांची सबसिडी लवकर मंजूर होते. आणखी योजना उघडण्यासाठी रोजचा हिशेब ठेवा!", pa: "750 ਤੋਂ ਉੱਪਰ ਸਕੋਰ ਵਾਲੇ ਕਿਸਾਨਾਂ ਦੀ ਸਬਸਿਡੀ ਜਲਦੀ ਪਾਸ ਹੁੰਦੀ ਹੈ। ਹੋਰ ਯੋਜਨਾਵਾਂ ਖੋਲ੍ਹਣ ਲਈ ਰੋਜ਼ ਦਾ ਹਿਸਾਬ ਰੱਖੋ!" },
  basedOnReadiness: { hi: "आपके प्रोफाइल के आधार पर", en: "Based on your Profile Readiness", mr: "तुमच्या प्रोफाईलवर आधारित", pa: "ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਦੇ ਅਧਾਰ ਤੇ" },
  unlocksAtScore: { hi: "{score} स्कोर पर खुलेगा", en: "Unlocks at {score} Score", mr: "{score} स्कोअरवर उघडेल", pa: "{score} ਸਕੋਰ 'ਤੇ ਖੁੱਲ੍ਹੇਗਾ" },
  keepRecording: { hi: "पात्र बनने के लिए हिसाब रखें", en: "Keep recording to be eligible", mr: "पात्र होण्यासाठी हिशेब ठेवा", pa: "ਯੋਗ ਬਣਨ ਲਈ ਹਿਸਾਬ ਰੱਖੋ" },
  keyBenefit: { hi: "मुख्य लाभ", en: "Key Benefit", mr: "मुख्य लाभ", pa: "ਮੁੱਖ ਲਾਭ" },

  // Missing Credit
  tierNeedsWork: { hi: "सुधार की जरूरत", en: "Needs Work", mr: "सुधारणेची गरज", pa: "ਸੁਧਾਰ ਦੀ ਲੋੜ" },
  tierFair: { hi: "ठीक", en: "Fair", mr: "ठीक", pa: "ਠੀਕ" },
  tierGood: { hi: "अच्छा", en: "Good", mr: "चांगले", pa: "ਚੰਗਾ" },
  tierExcellent: { hi: "उत्कृष्ट", en: "Excellent", mr: "उत्कृष्ट", pa: "ਬਹੁਤ ਵਧੀਆ" },
  profileReadiness: { hi: "प्रोफ़ाइल तैयारी", en: "Profile Readiness", mr: "प्रोफाइल तयारी", pa: "ਪ੍ਰੋਫਾਈਲ ਤਿਆਰੀ" },
  assessmentEngine: { hi: "मूल्यांकन इंजन", en: "Assessment Engine", mr: "मूल्यांकन इंजिन", pa: "ਮੁਲਾਂਕਣ ਇੰਜਣ" },
  outstandingRecords: { hi: "शानदार रिकॉर्ड। आपकी सभी सरकारी सब्सिडी जल्दी पास होंगी।", en: "Outstanding records. You are fast-tracked for all major government subsidies.", mr: "उत्कृष्ट रेकॉर्ड. तुम्हाला सर्व प्रमुख सरकारी सबसिडी लवकर मिळतील.", pa: "ਸ਼ਾਨਦਾਰ ਰਿਕਾਰਡ। ਤੁਹਾਡੀਆਂ ਸਾਰੀਆਂ ਸਰਕਾਰੀ ਸਬਸਿਡੀਆਂ ਜਲਦੀ ਪਾਸ ਹੋਣਗੀਆਂ।" },
  maintainKhata: { hi: "अपना स्कोर बढ़ाने और प्रीमियम सब्सिडी खोलने के लिए नियमित रूप से खाता बनाए रखें।", en: "Maintain your Khata regularly to boost your score and unlock premium subsidies.", mr: "तुमचा स्कोअर वाढवण्यासाठी आणि प्रीमियम सबसिडी अनलॉक करण्यासाठी नियमितपणे खाते अद्ययावत ठेवा.", pa: "ਆਪਣਾ ਸਕੋਰ ਵਧਾਉਣ ਅਤੇ ਪ੍ਰੀਮੀਅਮ ਸਬਸਿਡੀ ਖੋਲ੍ਹਣ ਲਈ ਨਿਯਮਿਤ ਤੌਰ 'ਤੇ ਖਾਤਾ ਬਣਾਈ ਰੱਖੋ।" },
  scoreDrivers: { hi: "स्कोर के कारण", en: "Score Drivers", mr: "स्कोअरची कारणे", pa: "ਸਕੋਰ ਦੇ ਕਾਰਨ" },
  settlingLoans: { hi: "समय पर लोन चुकाना सरकारी संस्थाओं को वित्तीय अनुशासन दिखाता है।", en: "Settling loans on time proves financial discipline to govt. bodies.", mr: "वेळेवर कर्ज फेडणे सरकारी संस्थांना आर्थिक शिस्त दाखवते.", pa: "ਸਮੇਂ ਸਿਰ ਕਰਜ਼ਾ ਮੋੜਨਾ ਸਰਕਾਰੀ ਸੰਸਥਾਵਾਂ ਨੂੰ ਵਿੱਤੀ ਅਨੁਸ਼ਾਸਨ ਦਿਖਾਉਂਦਾ ਹੈ।" },
  didYouKnow: { hi: "क्या आपको पता है?", en: "Did you know?", mr: "तुम्हाला माहीत आहे का?", pa: "ਕੀ ਤੁਹਾਨੂੰ ਪਤਾ ਹੈ?" },
  governmentBenefits: { hi: "सरकारी लाभ", en: "Government Benefits", mr: "सरकारी लाभ", pa: "ਸਰਕਾਰੀ ਲਾਭ" },
  checkEligibility: { hi: "पात्रता जांचें और आवेदन करें", en: "Check Eligibility & Apply", mr: "पात्रता तपासा आणि अर्ज करा", pa: "ਯੋਗਤਾ ਦੀ ਜਾਂਚ ਕਰੋ ਅਤੇ ਅਪਲਾਈ ਕਰੋ" },
  lockedStatus: { hi: "बंद है", en: "Locked", mr: "लॉक केलेले", pa: "ਬੰਦ ਹੈ" },
  // Quick Action Labels
  actionLedger: { hi: "खाता", en: "Ledger", mr: "खाते", pa: "ਖਾਤਾ" },
  actionWater: { hi: "पानी दिया", en: "Water", mr: "पाणी दिले", pa: "ਪਾਣੀ ਦਿੱਤਾ" },
  actionPesticide: { hi: "दवाई", en: "Pesticide", mr: "औषध", pa: "ਦਵਾਈ" },
  actionWorkers: { hi: "मजदूर", en: "Workers", mr: "मजूर", pa: "ਮਜ਼ਦੂਰ" },
  actionInventory: { hi: "भंडार", en: "Inventory", mr: "भांडार", pa: "ਭੰਡਾਰ" },
  actionBorrowings: { hi: "उधार", en: "Borrowings", mr: "उधार", pa: "ਉਧਾਰ" },

  // Landing Page keys
  features: { hi: "सुविधाएं", en: "Features", mr: "वैशिष्ट्ये", pa: "ਸੁਵਿਧਾਵਾਂ" },
  howItWorks: { hi: "यह कैसे काम करता है", en: "How it works", mr: "हे कसे काम करते", pa: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ" },
  stories: { hi: "किसानों की बातें", en: "Stories", mr: "शेतकऱ्यांच्या कथा", pa: "ਕਿਸਾਨਾਂ ਦੀਆਂ ਗੱਲਾਂ" },
  goToDashboard: { hi: "डैशबोर्ड पर जाएं", en: "Go to Dashboard", mr: "डॅशबोर्डवर जा", pa: "ਡੈਸ਼ਬੋਰਡ 'ਤੇ ਜਾਓ" },
  landingTitle: { hi: "खेती का पूरा हिसाब रखें, बिल्कुल फ्री!", en: "Manage Your Farm Easily, For Free!", mr: "शेतीचा पूर्ण हिशेब ठेवा, अगदी मोफत!", pa: "ਖੇਤੀ ਦਾ ਪੂਰਾ ਹਿਸਾਬ ਰੱਖੋ, ਬਿਲਕੁਲ ਮੁਫਤ!" },
  landingSubtitle: { hi: "खर्चा, आमदनी, और खेत का सारा काम अब आपके मोबाइल पर। अपनी खेती को बनाएं आसान और फायदेमंद।", en: "Track expenses, income, and daily tasks right from your mobile. Farming made simple and profitable.", mr: "खर्च, उत्पन्न आणि शेतातील सर्व कामे आता तुमच्या मोबाईलवर. शेती सोपी आणि फायदेशीर बनवा.", pa: "ਖਰਚਾ, ਕਮਾਈ, ਅਤੇ ਖੇਤ ਦਾ ਸਾਰਾ ਕੰਮ ਹੁਣ ਤੁਹਾਡੇ ਮੋਬਾਈਲ 'ਤੇ। ਆਪਣੀ ਖੇਤੀ ਨੂੰ ਬਣਾਓ ਆਸਾਨ ਅਤੇ ਫਾਇਦੇਮੰਦ।" },
  startManaging: { hi: "अभी शुरू करें", en: "Start Using for Free", mr: "आता सुरू करा", pa: "ਹੁਣੇ ਸ਼ੁਰੂ ਕਰੋ" },
  viewDemo: { hi: "डेमो देखें", en: "View Demo", mr: "डेमो पहा", pa: "ਡੈਮੋ ਦੇਖੋ" },
  enterpriseTools: { hi: "किसानों के लिए खास बनाया गया", en: "Built Specifically for Farmers", mr: "शेतकऱ्यांसाठी खास बनवलेले", pa: "ਕਿਸਾਨਾਂ ਲਈ ਖਾਸ ਬਣਾਇਆ ਗਿਆ" },
  enterpriseToolsDesc: { hi: "खेत से जुड़ा हर काम, जैसे बीज, खाद, पानी और मज़दूरी का हिसाब रखना अब बहुत आसान है।", en: "Everything you need to keep track of seeds, fertilizers, water, and labor in one simple place.", mr: "बियाणे, खत, पाणी आणि मजुरीचा हिशेब ठेवणे आता खूप सोपे आहे.", pa: "ਬੀਜ, ਖਾਦ, ਪਾਣੀ ਅਤੇ ਮਜ਼ਦੂਰੀ ਦਾ ਹਿਸਾਬ ਰੱਖਣਾ ਹੁਣ ਬਹੁਤ ਆਸਾਨ ਹੈ।" },
  financialAnalytics: { hi: "पैसे का पक्का हिसाब", en: "Track Every Rupee", mr: "पैशाचा पक्का हिशेब", pa: "ਪੈਸੇ ਦਾ ਪੱਕਾ ਹਿਸਾਬ" },
  financialAnalyticsDesc: { hi: "एक-एक रुपये का हिसाब रखें और जानें खेती में आपको कितना फायदा हुआ।", en: "Keep a daily record of your farming expenses and clearly see your total profit.", mr: "प्रत्येक रुपयाचा हिशेब ठेवा आणि शेतीत किती नफा झाला हे जाणून घ्या.", pa: "ਇੱਕ-ਇੱਕ ਰੁਪਏ ਦਾ ਹਿਸਾਬ ਰੱਖੋ ਅਤੇ ਜਾਣੋ ਖੇਤੀ ਵਿੱਚ ਤੁਹਾਨੂੰ ਕਿੰਨਾ ਫਾਇਦਾ ਹੋਇਆ।" },
  cropLifecycle: { hi: "फसल की पूरी जानकारी", en: "Crop Progress", mr: "पिकाची संपूर्ण माहिती", pa: "ਫ਼ਸਲ ਦੀ ਪੂਰੀ ਜਾਣਕਾਰੀ" },
  cropLifecycleDesc: { hi: "बुवाई से लेकर कटाई तक, हर काम को आसानी से दर्ज करें।", en: "Record daily activities from sowing to harvest, for multiple farms and seasons.", mr: "पेरणीपासून कापणीपर्यंत प्रत्येक काम सहज नोंदवा.", pa: "ਬਿਜਾਈ ਤੋਂ ਲੈ ਕੇ ਵਾਢੀ ਤੱਕ, ਹਰ ਕੰਮ ਨੂੰ ਆਸਾਨੀ ਨਾਲ ਦਰਜ ਕਰੋ।" },
  smartPlanning: { hi: "खेती की सही योजना", en: "Smart Farming", mr: "शेतीची योग्य योजना", pa: "ਖੇਤੀ ਦੀ ਸਹੀ ਯੋਜਨਾ" },
  smartPlanningDesc: { hi: "जानें कब क्या करना है, ताकि आपकी फसल और अच्छी हो।", en: "Know exactly what your farm needs to get better yields.", mr: "कधी काय करावे हे जाणून घ्या, जेणेकरून तुमचे पीक अधिक चांगले येईल.", pa: "ਜਾਣੋ ਕਦੋਂ ਕੀ ਕਰਨਾ ਹੈ, ਤਾਂ ਜੋ ਤੁਹਾਡੀ ਫ਼ਸਲ ਹੋਰ ਚੰਗੀ ਹੋਵੇ।" },
  mobileFirst: { hi: "चलाने में एकदम आसान", en: "Easy to Use on Mobile", mr: "वापरण्यास अगदी सोपे", pa: "ਚਲਾਉਣ ਵਿੱਚ ਬਿਲਕੁਲ ਆਸਾਨ" },
  mobileFirstDesc: { hi: "इसे आप सीधे अपने मोबाइल से कहीं भी और कभी भी चला सकते हैं।", en: "Works perfectly on your smartphone. Use it directly from the field.", mr: "तुम्ही ते थेट तुमच्या मोबाईलवरून कुठेही आणि कधीही वापरू शकता.", pa: "ਇਸਨੂੰ ਤੁਸੀਂ ਸਿੱਧੇ ਆਪਣੇ ਮੋਬਾਈਲ ਤੋਂ ਕਿਤੇ ਵੀ ਅਤੇ ਕਦੇ ਵੀ ਚਲਾ ਸਕਦੇ ਹੋ।" },
  securePrivate: { hi: "आपका डेटा एकदम सुरक्षित", en: "100% Safe & Secure", mr: "तुमचा डेटा पूर्णपणे सुरक्षित", pa: "ਤੁਹਾਡਾ ਡੇਟਾ ਬਿਲਕੁਲ ਸੁਰੱਖਿਅਤ" },
  securePrivateDesc: { hi: "आपका हिसाब सिर्फ आपके पास रहेगा, कोई और नहीं देख सकता।", en: "Your farming records are completely private and safe. Only you can see them.", mr: "तुमचा हिशेब फक्त तुमच्याकडे राहील, कोणीही पाहू शकत नाही.", pa: "ਤੁਹਾਡਾ ਹਿਸਾਬ ਸਿਰਫ ਤੁਹਾਡੇ ਕੋਲ ਰਹੇਗਾ, ਕੋਈ ਹੋਰ ਨਹੀਂ ਦੇਖ ਸਕਦਾ।" },
  readyTransform: { hi: "आज ही फ्री में शुरू करें", en: "Ready to simplify your farming?", mr: "आजच मोफत सुरू करा", pa: "ਅੱਜ ਹੀ ਮੁਫਤ ਵਿੱਚ ਸ਼ੁਰੂ ਕਰੋ" },
  readyTransformDesc: { hi: "हज़ारों किसानों की तरह आप भी अपनी खेती को आसान बनाएं। किसान डायरी का इस्तेमाल करना बिल्कुल फ्री है।", en: "Join thousands of farmers tracking their daily work with Kisan Diary. Best of all, it's 100% free forever.", mr: "हजारो शेतकऱ्यांप्रमाणे तुम्हीही तुमची शेती सोपी करा. किसान डायरी वापरणे पूर्णपणे मोफत आहे.", pa: "ਹਜ਼ਾਰਾਂ ਕਿਸਾਨਾਂ ਵਾਂਗ ਤੁਸੀਂ ਵੀ ਆਪਣੀ ਖੇਤੀ ਨੂੰ ਆਸਾਨ ਬਣਾਓ। ਕਿਸਾਨ ਡਾਇਰੀ ਦਾ ਇਸਤੇਮਾਲ ਕਰਨਾ ਬਿਲਕੁਲ ਮੁਫਤ ਹੈ।" },
  getStartedFree: { hi: "फ्री में खाता बनाएं", en: "Create Free Account", mr: "मोफत खाते तयार करा", pa: "ਮੁਫਤ ਵਿੱਚ ਖਾਤਾ ਬਣਾਓ" },
  pricingTitle: { hi: "आपके खेत के लिए सही योजना चुनें", en: "Choose the Right Plan for Your Farm", mr: "तुमच्या शेतासाठी योग्य योजना निवडा", pa: "ਆਪਣੇ ਖੇਤ ਲਈ ਸਹੀ ਯੋਜਨਾ ਚੁਣੋ" },
  pricingSubtitle: { hi: "हर किसान की ज़रूरत अलग होती है। हमारी योजनाएं छोटे किसान से लेकर बड़े खेत तक सभी के लिए बनाई गई हैं।", en: "Every farmer's needs are different. Our plans are designed for everyone — from small family farms to large agri-enterprises.", mr: "प्रत्येक शेतकऱ्याची गरज वेगळी असते. आमच्या योजना लहान शेतकऱ्यांपासून मोठ्या शेतांपर्यंत सर्वांसाठी बनवल्या आहेत.", pa: "ਹਰ ਕਿਸਾਨ ਦੀ ਜ਼ਰੂਰਤ ਵੱਖਰੀ ਹੁੰਦੀ ਹੈ। ਸਾਡੀਆਂ ਯੋਜਨਾਵਾਂ ਛੋਟੇ ਕਿਸਾਨ ਤੋਂ ਲੈ ਕੇ ਵੱਡੇ ਖੇਤ ਤੱਕ ਸਭ ਲਈ ਬਣਾਈਆਂ ਗਈਆਂ ਹਨ।" },
  pricingToggleMonthly: { hi: "मासिक", en: "Monthly", mr: "मासिक", pa: "ਮਹੀਨਾਵਾਰ" },
  pricingToggleYearly: { hi: "वार्षिक", en: "Yearly", mr: "वार्षिक", pa: "ਸਾਲਾਨਾ" },
  pricingYearlySave: { hi: "20% बचाएं", en: "Save 20%", mr: "२०% वाचवा", pa: "20% ਬਚਾਓ" },
  pricingMostPopular: { hi: "सबसे लोकप्रिय", en: "Most Popular", mr: "सर्वाधिक लोकप्रिय", pa: "ਸਭ ਤੋਂ ਵੱਧ ਪ੍ਰਸਿੱਧ" },
  pricingFreeName: { hi: "किसान", en: "Kisan", mr: "किसान", pa: "ਕਿਸਾਨ" },
  pricingFreeDesc: { hi: "छोटे किसानों के लिए, एक से दो खेत", en: "Perfect for small farmers with 1-2 farms", mr: "लहान शेतकऱ्यांसाठी, एक ते दोन शेत", pa: "ਛੋਟੇ ਕਿਸਾਨਾਂ ਲਈ, ਇੱਕ ਤੋਂ ਦੋ ਖੇਤ" },
  pricingFreePrice: { hi: "₹0", en: "₹0", mr: "₹०", pa: "₹0" },
  pricingFreePer: { hi: "हमेशा के लिए फ्री", en: "Free Forever", mr: "कायमसाठी मोफत", pa: "ਹਮੇਸ਼ਾ ਲਈ ਮੁਫਤ" },
  pricingProName: { hi: "किसान Pro", en: "Kisan Pro", mr: "किसान Pro", pa: "ਕਿਸਾਨ Pro" },
  pricingProDesc: { hi: "बड़े किसानों के लिए, असीमित खेत और फसलें", en: "For growing farmers with unlimited farms & seasons", mr: "मोठ्या शेतकऱ्यांसाठी, अमर्यादित शेत आणि पिके", pa: "ਵੱਡੇ ਕਿਸਾਨਾਂ ਲਈ, ਅਸੀਮਤ ਖੇਤ ਅਤੇ ਫ਼ਸਲਾਂ" },
  pricingProMonthlyPrice: { hi: "₹199", en: "₹199", mr: "₹१९९", pa: "₹199" },
  pricingProYearlyPrice: { hi: "₹159", en: "₹159", mr: "₹१५९", pa: "₹159" },
  pricingProPer: { hi: "प्रति माह", en: "per month", mr: "दरमहा", pa: "ਪ੍ਰਤੀ ਮਹੀਨਾ" },
  pricingEnterName: { hi: "एग्री-एंटरप्राइज़", en: "Agri-Enterprise", mr: "अ‍ॅग्री-एंटरप्राइज", pa: "ਐਗਰੀ-ਐਂਟਰਪ੍ਰਾਈਜ਼" },
  pricingEnterDesc: { hi: "कृषि व्यवसायों और FPO के लिए", en: "For agri-businesses, FPOs, and cooperatives", mr: "कृषी व्यवसाय आणि FPO साठी", pa: "ਖੇਤੀਬਾੜੀ ਕਾਰੋਬਾਰਾਂ ਅਤੇ FPO ਲਈ" },
  pricingEnterPrice: { hi: "कस्टम", en: "Custom", mr: "कस्टम", pa: "ਕਸਟਮ" },
  pricingEnterPer: { hi: "हमसे संपर्क करें", en: "Contact us", mr: "आमच्याशी संपर्क साधा", pa: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ" },
  pricingCtaFree: { hi: "अभी शुरू करें - फ्री है!", en: "Get Started — It's Free!", mr: "आता सुरू करा - मोफत आहे!", pa: "ਹੁਣੇ ਸ਼ੁਰੂ ਕਰੋ - ਮੁਫਤ ਹੈ!" },
  pricingCtaPro: { hi: "Pro शुरू करें", en: "Start Pro Plan", mr: "Pro सुरू करा", pa: "Pro ਸ਼ੁਰੂ ਕਰੋ" },
  pricingCtaEnterprise: { hi: "बात करें", en: "Talk to Sales", mr: "बोलणी करा", pa: "ਗੱਲ ਕਰੋ" },
  pricingFaq: { hi: "अक्सर पूछे जाने वाले सवाल", en: "Frequently Asked Questions", mr: "वारंवार विचारले जाणारे प्रश्न", pa: "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ" },
  pricingFaqQ1: { hi: "क्या Kisan Diary वाकई मुफ्त है?", en: "Is Kisan Diary really free?", mr: "Kisan Diary खरोखर मोफत आहे का?", pa: "ਕੀ Kisan Diary ਸੱਚਮੁੱਚ ਮੁਫਤ ਹੈ?" },
  pricingFaqA1: { hi: "हाँ! किसान योजना हमेशा के लिए पूरी तरह मुफ्त है। कोई छिपी फीस नहीं, कोई क्रेडिट कार्ड नहीं।", en: "Yes! The Kisan plan is completely free forever. No hidden fees, no credit card required.", mr: "होय! किसान योजना कायमसाठी पूर्णपणे मोफत आहे. कोणतेही छुपे शुल्क नाही, क्रेडिट कार्डची आवश्यकता नाही.", pa: "ਹਾਂ! ਕਿਸਾਨ ਯੋਜਨਾ ਹਮੇਸ਼ਾ ਲਈ ਪੂਰੀ ਤਰ੍ਹਾਂ ਮੁਫਤ ਹੈ। ਕੋਈ ਛੁਪੀ ਹੋਈ ਫੀਸ ਨਹੀਂ, ਕੋਈ ਕ੍ਰੈਡਿਟ ਕਾਰਡ ਨਹੀਂ।" },
  pricingFaqQ2: { hi: "क्या मैं कभी भी अपग्रेड या डाउनग्रेड कर सकता हूं?", en: "Can I upgrade or downgrade anytime?", mr: "मी कधीही अपग्रेड किंवा डाउनग्रेड करू शकतो का?", pa: "ਕੀ ਮੈਂ ਕਦੇ ਵੀ ਅਪਗ੍ਰੇਡ ਜਾਂ ਡਾਊਨਗ੍ਰੇਡ ਕਰ ਸਕਦਾ ਹਾਂ?" },
  pricingFaqA2: { hi: "बिल्कुल! आप जब चाहें अपनी योजना बदल सकते हैं। अगर आप डाउनग्रेड करते हैं, तो शेष राशि अगले बिलिंग चक्र में समायोजित हो जाती है।", en: "Absolutely! You can change your plan at any time. If you downgrade, remaining credit is adjusted into the next billing cycle.", mr: "नक्कीच! तुम्ही कधीही तुमची योजना बदलू शकता. जर तुम्ही डाउनग्रेड केले, तर उरलेली रक्कम पुढील बिलिंग सायकलमध्ये समायोजित केली जाईल.", pa: "ਬਿਲਕੁਲ! ਤੁਸੀਂ ਜਦੋਂ ਚਾਹੋ ਆਪਣੀ ਯੋਜਨਾ ਬਦਲ ਸਕਦੇ ਹੋ। ਜੇਕਰ ਤੁਸੀਂ ਡਾਊਨਗ੍ਰੇਡ ਕਰਦੇ ਹੋ, ਤਾਂ ਬਕਾਇਆ ਰਾਸ਼ੀ ਅਗਲੇ ਬਿਲਿੰਗ ਚੱਕਰ ਵਿੱਚ ਐਡਜਸਟ ਹੋ ਜਾਂਦੀ ਹੈ।" },
  pricingFaqQ3: { hi: "क्या मेरा डेटा सुरक्षित है?", en: "Is my data safe?", mr: "माझा डेटा सुरक्षित आहे का?", pa: "ਕੀ ਮੇਰਾ ਡੇਟਾ ਸੁਰੱਖਿਅਤ ਹੈ?" },
  pricingFaqA3: { hi: "आपका डेटा एंड-टू-एंड एन्क्रिप्टेड है और हमारे सुरक्षित भारतीय सर्वर पर संग्रहीत है। हम कभी भी आपका डेटा तीसरे पक्ष के साथ साझा नहीं करते।", en: "Your data is end-to-end encrypted and stored on our secure Indian servers. We never share your data with third parties.", mr: "तुमचा डेटा एंड-टू-एंड एन्क्रिप्टेड आहे आणि आमच्या सुरक्षित भारतीय सर्व्हरवर संग्रहित आहे. आम्ही तुमचा डेटा कधीही तृतीय पक्षांसोबत शेअर करत नाही.", pa: "ਤੁਹਾਡਾ ਡੇਟਾ ਐਂਡ-ਟੂ-ਐਂਡ ਐਨਕ੍ਰਿਪਟਡ ਹੈ ਅਤੇ ਸਾਡੇ ਸੁਰੱਖਿਅਤ ਭਾਰਤੀ ਸਰਵਰਾਂ 'ਤੇ ਸਟੋਰ ਹੈ। ਅਸੀਂ ਕਦੇ ਵੀ ਤੁਹਾਡਾ ਡੇਟਾ ਤੀਜੀ ਧਿਰ ਨਾਲ ਸਾਂਝਾ ਨਹੀਂ ਕਰਦੇ।" },
  landTypeOwned: { hi: "अपनी ज़मीन (Owned)", en: "Owned Land", mr: "स्वतःची जमीन (Owned)", pa: "ਆਪਣੀ ਜ਼ਮੀਨ (Owned)" },
  landTypeLeased: { hi: "किराये की ज़मीन (Leased)", en: "Leased Land", mr: "भाड्याची जमीन (Leased)", pa: "ਕਿਰਾਏ ਦੀ ਜ਼ਮੀਨ (Leased)" },
  landTypeAncestral: { hi: "पुश्तैनी ज़मीन (Ancestral)", en: "Ancestral Land", mr: "वडिलोपार्जित जमीन (Ancestral)", pa: "ਪੁਰਖਿਆਂ ਦੀ ਜ਼ਮੀਨ (Ancestral)" },
  irrigationBorewell: { hi: "बोरवेल (Borewell)", en: "Borewell", mr: "बोरवेल (Borewell)", pa: "ਬੋਰਵੈੱਲ (Borewell)" },
  irrigationCanal: { hi: "नहर (Canal)", en: "Canal", mr: "कालवा (Canal)", pa: "ਨਹਿਰ (Canal)" },
  irrigationRainFed: { hi: "बारिश पर निर्भर (Rain-fed)", en: "Rain-fed", mr: "पावसावर अवलंबून (Rain-fed)", pa: "ਮੀਂਹ ਤੇ ਨਿਰਭਰ (Rain-fed)" },
  irrigationDrip: { hi: "ड्रिप सिंचाई (Drip Irrigation)", en: "Drip Irrigation", mr: "ठिबक सिंचन (Drip)", pa: "ਡ੍ਰਿੱਪ ਸਿੰਚਾਈ (Drip)" },
  irrigationPond: { hi: "तालाब (Pond/Tank)", en: "Pond/Tank", mr: "तलाव (Pond/Tank)", pa: "ਤਾਲਾਬ (Pond/Tank)" },
  soilBlack: { hi: "काली मिट्टी (Black Soil)", en: "Black Soil", mr: "काळी माती (Black Soil)", pa: "ਕਾਲੀ ਮਿੱਟੀ (Black Soil)" },
  soilRed: { hi: "लाल मिट्टी (Red Soil)", en: "Red Soil", mr: "लाल माती (Red Soil)", pa: "ਲਾਲ ਮਿੱਟੀ (Red Soil)" },
  soilSandy: { hi: "रेतीली मिट्टी (Sandy)", en: "Sandy", mr: "वाळूची माती (Sandy)", pa: "ਰੇਤਲੀ ਮਿੱਟੀ (Sandy)" },
  soilClay: { hi: "चिकनी मिट्टी (Clay)", en: "Clay", mr: "चिकणमाती (Clay)", pa: "ਚੀਕਣੀ ਮਿੱਟੀ (Clay)" },
  soilAlluvial: { hi: "दोमट मिट्टी (Alluvial/Loamy)", en: "Alluvial/Loamy", mr: "गाळाची माती (Alluvial/Loamy)", pa: "ਦੋਮਟ ਮਿੱਟੀ (Alluvial/Loamy)" },
  unitAcre: { hi: "एकड़ (Acre)", en: "Acre", mr: "एकर (Acre)", pa: "ਏਕੜ (Acre)" },
  unitBigha: { hi: "बीघा (Bigha)", en: "Bigha", mr: "बिघा (Bigha)", pa: "ਬੀਘਾ (Bigha)" },
  unitHectare: { hi: "हेक्टेयर (Hectare)", en: "Hectare", mr: "हेक्टर (Hectare)", pa: "ਹੈਕਟੇਅਰ (Hectare)" },
  saveFailed: { hi: "सहेजने में विफल", en: "Failed to save", mr: "सेव्ह करण्यात अयशस्वी", pa: "ਸੇਵ ਕਰਨ ਵਿੱਚ ਅਸਫਲ" },
  labelFullName: { hi: "पूरा नाम", en: "Full Name", mr: "पूर्ण नाव", pa: "ਪੂਰਾ ਨਾਮ" },
  phFullName: { hi: "अपना नाम डालें", en: "Enter your name", mr: "तुमचे नाव टाका", pa: "ਆਪਣਾ ਨਾਮ ਦਰਜ ਕਰੋ" },
  labelMobile: { hi: "मोबाइल नंबर", en: "Mobile Number", mr: "मोबाईल क्रमांक", pa: "ਮੋਬਾਈਲ ਨੰਬਰ" },
  labelPincode: { hi: "पिन कोड (PIN Code)", en: "PIN Code", mr: "पिन कोड (PIN Code)", pa: "ਪਿਨ ਕੋਡ (PIN Code)" },
  phPincode: { hi: "6 अंकों का पिन कोड", en: "6 digit PIN code", mr: "6 अंकी पिन कोड", pa: "6 ਅੰਕਾਂ ਦਾ ਪਿਨ ਕੋਡ" },
  labelDistrict: { hi: "जिला (District)", en: "District", mr: "जिल्हा (District)", pa: "ਜ਼ਿਲ੍ਹਾ (District)" },
  phDistrict: { hi: "अपना जिला लिखें", en: "Enter your district", mr: "तुमचा जिल्हा लिहा", pa: "ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ ਲਿਖੋ" },
  labelVillage: { hi: "गाँव/कस्बा (Village)", en: "Village/Town", mr: "गाव/शहर (Village)", pa: "ਪਿੰਡ/ਕਸਬਾ (Village)" },
  phVillage: { hi: "गाँव का नाम लिखें", en: "Enter village name", mr: "गावाचे नाव लिहा", pa: "ਪਿੰਡ ਦਾ ਨਾਮ ਲਿਖੋ" },
  labelState: { hi: "राज्य (State)", en: "State", mr: "राज्य (State)", pa: "ਰਾਜ (State)" },
  phState: { hi: "राज्य चुनें", en: "Select state", mr: "राज्य निवडा", pa: "ਰਾਜ ਚੁਣੋ" },
  labelOptional: { hi: "वैकल्पिक", en: "Optional", mr: "पर्यायी", pa: "ਵਿਕਲਪਿਕ" },
  labelPmKisanId: { hi: "PM Kisan रजिस्ट्रेशन ID", en: "PM Kisan Registration ID", mr: "PM किसान नोंदणी ID", pa: "PM ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ID" },
  phPmKisanId: { hi: "ID नंबर डालें (अगर है)", en: "Enter ID (if any)", mr: "आयडी नंबर टाका (असल्यास)", pa: "ID ਨੰਬਰ ਦਰਜ ਕਰੋ (ਜੇਕਰ ਹੈ)" },
  pmKisanHelpText: { hi: "PM Kisan ID होने पर सरकारी योजनाओं का मिलान बेहतर होगा।", en: "Having PM Kisan ID helps better match with govt schemes.", mr: "PM किसान आयडी असल्यास सरकारी योजनांशी जुळणी चांगली होईल.", pa: "PM ਕਿਸਾਨ ID ਹੋਣ ਨਾਲ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਦਾ ਮੇਲ ਬਿਹਤਰ ਹੋਵੇਗਾ।" },
  errFarmInfoReq: { hi: "खेत का नाम, आकार और स्थान जरूरी है।", en: "Farm name, size, and location are required.", mr: "शेतचे नाव, आकार आणि स्थान आवश्यक आहे.", pa: "ਖੇਤ ਦਾ ਨਾਮ, ਆਕਾਰ ਅਤੇ ਸਥਾਨ ਜ਼ਰੂਰੀ ਹੈ।" },
  errFarmAddFail: { hi: "खेत जोड़ने में गड़बड़ी हुई। फिर कोशिश करें।", en: "Failed to add farm. Try again.", mr: "शेत जोडण्यात अडचण आली. पुन्हा प्रयत्न करा.", pa: "ਖੇਤ ਜੋੜਨ ਵਿੱਚ ਸਮੱਸਿਆ ਆਈ। ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।" },
  errFarmUpdateFail: { hi: "खेत अपडेट करने में विफल।", en: "Failed to update farm.", mr: "शेत अपडेट करण्यात अयशस्वी.", pa: "ਖੇਤ ਅੱਪਡੇਟ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।" },
  errSeasonInfoReq: { hi: "फसल का नाम और तारीख जरूरी है।", en: "Crop name and date are required.", mr: "पिकाचे नाव आणि तारीख आवश्यक आहे.", pa: "ਫ਼ਸਲ ਦਾ ਨਾਮ ਅਤੇ ਮਿਤੀ ਜ਼ਰੂਰੀ ਹੈ।" },
  errSeasonAddFail: { hi: "फसल शुरू करने में विफल।", en: "Failed to start season.", mr: "पीक सुरू करण्यात अयशस्वी.", pa: "ਫ਼ਸਲ ਸ਼ੁਰੂ ਕਰਨ ਵਿੱਚ ਅਸਫਲ।" },
  myFarmsTitle: { hi: "मेरे खेत", en: "My Farms", mr: "माझी शेती", pa: "ਮੇਰੇ ਖੇਤ" },
  btnNewFarm: { hi: "नया खेत", en: "New Farm", mr: "नवीन शेत", pa: "ਨਵਾਂ ਖੇਤ" },
  noFarmsFound: { hi: "कोई खेत नहीं", en: "No Farms", mr: "कोणतेही शेत नाही", pa: "ਕੋਈ ਖੇਤ ਨਹੀਂ" },
  noFarmsDesc: { hi: "पहला खेत जोड़ें और खेती का हिसाब शुरू करें।", en: "Add your first farm and start tracking.", mr: "पहिले शेत जोडा आणि शेतीचा हिशेब सुरू करा.", pa: "ਪਹਿਲਾ ਖੇਤ ਜੋੜੋ ਅਤੇ ਖੇਤੀ ਦਾ ਹਿਸਾਬ ਸ਼ੁਰੂ ਕਰੋ।" },
  btnAddFirstFarm: { hi: "पहला खेत जोड़ें", en: "Add First Farm", mr: "पहिले शेत जोडा", pa: "ਪਹਿਲਾ ਖੇਤ ਜੋੜੋ" },
  badgeSelected: { hi: "चयनित", en: "Selected", mr: "निवडलेले", pa: "ਚੁਣਿਆ ਗਿਆ" },
  labelActiveSeason: { hi: "चालू फसल", en: "Active Season", mr: "सध्याचे पीक", pa: "ਚਾਲੂ ਫ਼ਸਲ" },
  labelFromDate: { hi: "से", en: "Since", mr: "पासून", pa: "ਤੋਂ" },
  btnCompleteSeason: { hi: "फसल पूरी करें", en: "Complete Season", mr: "पीक पूर्ण करा", pa: "ਫ਼ਸਲ ਪੂਰੀ ਕਰੋ" },
  btnStartSeason: { hi: "फसल शुरू करें", en: "Start Season", mr: "पीक सुरू करा", pa: "ਫ਼ਸਲ ਸ਼ੁਰੂ ਕਰੋ" },
  modalTitleAddFarm: { hi: "नया खेत जोड़ें", en: "Add New Farm", mr: "नवीन शेत जोडा", pa: "ਨਵਾਂ ਖੇਤ ਜੋੜੋ" },
  modalDescAddFarm: { hi: "खेत की जानकारी भरें", en: "Fill farm details", mr: "शेताची माहिती भरा", pa: "ਖੇਤ ਦੀ ਜਾਣਕਾਰੀ ਭਰੋ" },
  labelFarmNameStar: { hi: "खेत का नाम *", en: "Farm Name *", mr: "शेताचे नाव *", pa: "ਖੇਤ ਦਾ ਨਾਮ *" },
  btnSaveFarm: { hi: "सुरक्षित करें", en: "Save", mr: "सेव्ह करा", pa: "ਸੁਰੱਖਿਅਤ ਕਰੋ" },
  modalTitleEditFarm: { hi: "खेत संपादित करें", en: "Edit Farm", mr: "शेत संपादित करा", pa: "ਖੇਤ ਸੰਪਾਦਿਤ ਕਰੋ" },
  btnUpdateFarm: { hi: "अपडेट करें", en: "Update", mr: "अपडेट करा", pa: "ਅੱਪਡੇਟ ਕਰੋ" },
  modalTitleDeleteFarm: { hi: "खेत हटाएं?", en: "Delete Farm?", mr: "शेत हटवा?", pa: "ਖੇਤ ਹਟਾਓ?" },
  btnCancel: { hi: "रद्द करें", en: "Cancel", mr: "रद्द करा", pa: "ਰੱਦ ਕਰੋ" },
  modalTitleCompleteSeason: { hi: "फसल पूरी करें?", en: "Complete Season?", mr: "पीक पूर्ण करा?", pa: "ਫ਼ਸਲ ਪੂਰੀ ਕਰੋ?" },
  msgCompleteSeasonDesc: { hi: "की फसल को पूर्ण मार्क करेंगे। बाद", en: "will be marked as complete. Then you can", mr: "च्या पिकाला पूर्ण म्हणून मार्क केले जाईल. नंतर तुम्ही", pa: "ਦੀ ਫ਼ਸਲ ਨੂੰ ਪੂਰਨ ਮੰਨਿਆ ਜਾਵੇਗਾ। ਫਿਰ ਤੁਸੀਂ" },
  btnViewDetails: { hi: "विस्तार देखें", en: "View Details", mr: "सविस्तर पहा", pa: "ਵੇਰਵੇ ਦੇਖੋ" },
  notifMandiTitle: { hi: "मंडी भाव अलर्ट", en: "Mandi Price Alerts", mr: "मंडी भाव अलर्ट", pa: "ਮੰਡੀ ਭਾਅ ਅਲਰਟ" },
  notifMandiDesc: { hi: "फसल की कीमत में बड़ा बदलाव होने पर सूचना", en: "Notify when there is a major price change", mr: "पिकाच्या किमतीत मोठा बदल झाल्यास सूचना", pa: "ਫ਼ਸਲ ਦੀ ਕੀਮਤ ਵਿੱਚ ਵੱਡਾ ਬਦਲਾਅ ਆਉਣ ਤੇ ਸੂਚਨਾ" },
  notifWeatherTitle: { hi: "मौसम चेतावनी", en: "Weather Alerts", mr: "हवामान सूचना", pa: "ਮੌਸਮ ਚਿਤਾਵਨੀ" },
  notifWeatherDesc: { hi: "बारिश या गर्मी की चेतावनी मिलने पर अलर्ट", en: "Alert on rain or heat warnings", mr: "पाऊस किंवा उष्णतेचा इशारा मिळाल्यास अलर्ट", pa: "ਮੀਂਹ ਜਾਂ ਗਰਮੀ ਦੀ ਚਿਤਾਵਨੀ ਮਿਲਣ ਤੇ ਅਲਰਟ" },
  notifDebtTitle: { hi: "उधार याद दिलाना", en: "Debt Reminders", mr: "कर्ज स्मरणपत्र", pa: "ਉਧਾਰ ਯਾਦ ਕਰਵਾਉਣਾ" },
  notifDebtDesc: { hi: "उधार की तारीख से 3 दिन पहले रिमाइंडर", en: "Reminder 3 days before due date", mr: "कर्जाच्या तारखेच्या 3 दिवस आधी स्मरणपत्र", pa: "ਉਧਾਰ ਦੀ ਤਰੀਕ ਤੋਂ 3 ਦਿਨ ਪਹਿਲਾਂ ਰਿਮਾਈਂਡਰ" },
  notifDailyTitle: { hi: "दैनिक काम रिमाइंडर", en: "Daily Task Reminder", mr: "दैनंदिन काम स्मरणपत्र", pa: "ਰੋਜ਼ਾਨਾ ਕੰਮ ਰਿਮਾਈਂਡਰ" },
  notifDailyDesc: { hi: "शाम 6 बजे: 'आज का काम लिखा?' रिमाइंडर", en: "6 PM: 'Logged today's task?' reminder", mr: "संध्याकाळी 6 वाजता: 'आजचे काम लिहिले?' स्मरणपत्र", pa: "ਸ਼ਾਮ 6 ਵਜੇ: 'ਅੱਜ ਦਾ ਕੰਮ ਲਿਖਿਆ?' ਰਿਮਾਈਂਡਰ" },
  notifStockTitle: { hi: "भंडार कम होने का अलर्ट", en: "Low Stock Alert", mr: "स्टॉक कमी असल्याचा अलर्ट", pa: "ਸਟਾਕ ਘੱਟ ਹੋਣ ਦਾ ਅਲਰਟ" },
  notifStockDesc: { hi: "बीज, खाद या दवाई का स्टॉक कम होने पर", en: "When seeds, fertilizers, or pesticides are low", mr: "बियाणे, खते किंवा औषधांचा स्टॉक कमी असल्यास", pa: "ਬੀਜ, ਖਾਦ ਜਾਂ ਦਵਾਈ ਦਾ ਸਟਾਕ ਘੱਟ ਹੋਣ ਤੇ" },
  unitPreferenceDesc: { hi: "सभी खेतों का आकार चुनी हुई इकाई में दिखेगा।", en: "All farm sizes will be shown in the selected unit.", mr: "सर्व शेतांचा आकार निवडलेल्या एककात दिसेल.", pa: "ਸਾਰੇ ਖੇਤਾਂ ਦਾ ਆਕਾਰ ਚੁਣੀ ਹੋਈ ਇਕਾਈ ਵਿੱਚ ਦਿਖੇਗਾ।" },
  errPinMismatch: { hi: "नया PIN दोनों में एक जैसा होना चाहिए।", en: "New PIN must match in both fields.", mr: "नवीन पिन दोन्ही फील्डमध्ये समान असावा.", pa: "ਨਵਾਂ PIN ਦੋਵਾਂ ਖੇਤਰਾਂ ਵਿੱਚ ਇੱਕੋ ਜਿਹਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।" },
  errPinLength: { hi: "PIN कम से कम 4 अंकों का होना चाहिए।", en: "PIN must be at least 4 digits.", mr: "पिन किमान 4 अंकी असावा.", pa: "PIN ਘੱਟੋ ਘੱਟ 4 ਅੰਕਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।" },
  errPinChangeFail: { hi: "PIN बदलने में विफल।", en: "Failed to change PIN.", mr: "पिन बदलण्यात अयशस्वी.", pa: "PIN ਬਦਲਣ ਵਿੱਚ ਅਸਫਲ।" },
  encryptedSecure: { hi: "एन्क्रिप्टेड और सुरक्षित", en: "Encrypted & Secure", mr: "एनक्रिप्टेड आणि सुरक्षित", pa: "ਐਨਕ੍ਰਿਪਟਡ ਅਤੇ ਸੁਰੱਖਿਅਤ" },
  btnChangePin: { hi: "PIN बदलें", en: "Change PIN", mr: "पिन बदला", pa: "PIN ਬਦਲੋ" },
  btnUpdatePin: { hi: "PIN अपडेट करें", en: "Update PIN", mr: "पिन अपडेट करा", pa: "PIN ਅੱਪਡੇਟ ਕਰੋ" },
  helpSupport: { hi: "सहायता और सपोर्ट", en: "Help & Support", mr: "मदत आणि सपोर्ट", pa: "ਮਦਦ ਅਤੇ ਸਪੋਰਟ" },
  helpWhatsApp: { hi: "WhatsApp पर मदद लें", en: "Get help on WhatsApp", mr: "WhatsApp वर मदत मिळवा", pa: "WhatsApp ਤੇ ਮਦਦ ਲਵੋ" },
  privacyPolicy: { hi: "प्राइवेसी पॉलिसी", en: "Privacy Policy", mr: "गोपनीयता धोरण", pa: "ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ" },
  privacyDesc: { hi: "आपके डेटा की सुरक्षा के बारे में", en: "About your data security", mr: "तुमच्या डेटाच्या सुरक्षेबद्दल", pa: "ਤੁਹਾਡੇ ਡੇਟਾ ਦੀ ਸੁਰੱਖਿਆ ਬਾਰੇ" },
  termsConditions: { hi: "उपयोग की शर्तें", en: "Terms of Use", mr: "वापराच्या अटी", pa: "ਵਰਤੋਂ ਦੀਆਂ ਸ਼ਰਤਾਂ" },
  aboutKisanScore: { hi: "किसान स्कोर के बारे में", en: "About Kisan Score", mr: "किसान स्कोअर बद्दल", pa: "ਕਿਸਾਨ ਸਕੋਰ ਬਾਰੇ" },
  howScoreWorks: { hi: "स्कोर कैसे काम करता है?", en: "How does the score work?", mr: "स्कोअर कसे काम करते?", pa: "ਸਕੋਰ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ?" },
  loginRequired: { hi: "लॉगिन आवश्यक है", en: "Login Required", mr: "लॉगिन आवश्यक आहे", pa: "ਲੌਗਇਨ ਜ਼ਰੂਰੀ ਹੈ" },
  btnLogout: { hi: "लॉगआउट (Logout)", en: "Logout", mr: "लॉगआउट (Logout)", pa: "ਲੌਗਆਉਟ (Logout)" },
  crop_wheat: { hi: "गेहूँ", en: "Wheat", mr: "गहू", pa: "ਕਣਕ" },
  crop_rice: { hi: "धान (चावल)", en: "Rice (Paddy)", mr: "भात (तांदूळ)", pa: "ਝੋਨਾ (ਚੌਲ)" },
  crop_soyabean: { hi: "सोयाबीन", en: "Soyabean", mr: "सोयाबीन", pa: "ਸੋਇਆਬੀਨ" },
  crop_cotton: { hi: "कपास", en: "Cotton", mr: "कापूस", pa: "ਕਪਾਹ" },
  crop_maize: { hi: "मक्का", en: "Maize", mr: "मका", pa: "ਮੱਕੀ" },
  crop_mustard: { hi: "सरसों", en: "Mustard", mr: "मोहरी", pa: "ਸਰ੍ਹੋਂ" },
  crop_gram: { hi: "चना", en: "Gram", mr: "हरभरा", pa: "ਛੋਲੇ" },
  crop_onion: { hi: "प्याज़", en: "Onion", mr: "कांदा", pa: "ਪਿਆਜ਼" },
  crop_potato: { hi: "आलू", en: "Potato", mr: "बटाटा", pa: "ਆਲੂ" },
  crop_tur: { hi: "अरहर (तूर)", en: "Tur (Arhar)", mr: "तूर", pa: "ਅਰਹਰ (ਤੂਰ)" },
  rec_sell: { hi: "अभी बेचें", en: "Sell Now", mr: "आत्ता विका", pa: "ਹੁਣ ਵੇਚੋ" },
  rec_wait: { hi: "इंतज़ार करें", en: "Wait", mr: "वाट पाहा", pa: "ਉਡੀਕ ਕਰੋ" },
  rec_good: { hi: "सही दाम", en: "Good Price", mr: "चांगला दर", pa: "ਸਹੀ ਕੀਮਤ" },
  day_SUN: { hi: "रवि", en: "SUN", mr: "रवि", pa: "ਐਤ" },
  day_MON: { hi: "सोम", en: "MON", mr: "सोम", pa: "ਸੋਮ" },
  day_TUE: { hi: "मंगल", en: "TUE", mr: "मंगळ", pa: "ਮੰਗਲ" },
  day_WED: { hi: "बुध", en: "WED", mr: "बुध", pa: "ਬੁੱਧ" },
  day_THU: { hi: "गुरु", en: "THU", mr: "गुरू", pa: "ਵੀਰ" },
  day_FRI: { hi: "शुक्र", en: "FRI", mr: "शुक्र", pa: "ਸ਼ੁੱਕਰ" },
  day_SAT: { hi: "शनि", en: "SAT", mr: "शनी", pa: "ਸ਼ਨਿਚਰ" },
  day_TDY: { hi: "आज", en: "TDY", mr: "आज", pa: "ਅੱਜ" },
  day_YST: { hi: "कल", en: "YST", mr: "काल", pa: "ਕੱਲ੍ਹ" },
  advisory_up: { hi: "{crop} के दाम आज ₹{change} बढ़े हैं। मंडी में बेचने का सही समय है।", en: "{crop} prices are up by ₹{change} today. Good time to sell at the Mandi.", mr: "आज {crop} चे दर ₹{change} नी वाढले आहेत. मंडीत विकण्याची योग्य वेळ आहे.", pa: "{crop} ਦੇ ਭਾਅ ਅੱਜ ₹{change} ਵਧੇ ਹਨ। ਮੰਡੀ ਵਿੱਚ ਵੇਚਣ ਦਾ ਸਹੀ ਸਮਾਂ ਹੈ।" },
  advisory_down: { hi: "{crop} के दाम ₹{change} गिरे हैं। बेचने से पहले कुछ दिन रुकें।", en: "{crop} prices dropped by ₹{change}. Wait a few days before selling.", mr: "{crop} चे दर ₹{change} नी घसरले आहेत. विकण्यापूर्वी काही दिवस थांबा.", pa: "{crop} ਦੇ ਭਾਅ ₹{change} ਡਿੱਗੇ ਹਨ। ਵੇਚਣ ਤੋਂ ਪਹਿਲਾਂ ਕੁਝ ਦਿਨ ਰੁਕੋ।" },
  advisory_stable: { hi: "आज मंडी में भाव स्थिर हैं। कोई बड़ी गिरावट नहीं हुई।", en: "Market is steady today. No major price drops. Good day for routine Mandi visits.", mr: "आज मंडीत दर स्थिर आहेत. कोणतीही मोठी घसरण नाही.", pa: "ਅੱਜ ਮੰਡੀ ਵਿੱਚ ਭਾਅ ਸਥਿਰ ਹਨ। ਕੋਈ ਵੱਡੀ ਗਿਰਾਵਟ ਨਹੀਂ ਹੋਈ।" },
};

let output = `export const translations = {\n`;
['hi', 'en', 'mr', 'pa'].forEach(lang => {
  output += `  ${lang}: {\n`;
  for (const [key, trans] of Object.entries(baseKeys)) {
    output += `    ${key}: ${JSON.stringify(trans[lang] || key)},\n`;
  }
  output += `  },\n`;
});
output += `};

export type Language = keyof typeof translations;
export type TranslationKey = keyof (typeof translations)["hi"];

export function t(lang: Language | undefined | null | string, key: TranslationKey): string {
  const safeLang = (lang && (lang in translations)) ? (lang as Language) : "hi";
  return (translations[safeLang] as any)[key] || (translations.hi as any)[key] || key;
}

export const INDIAN_STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka",
  "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram",
  "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu",
  "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal",
  "Delhi", "Jammu & Kashmir", "Ladakh", "Puducherry"
];

export const LANGUAGES = [
  { code: "hi", name: "हिंदी", englishName: "Hindi" },
  { code: "en", name: "English", englishName: "English" },
  { code: "mr", name: "मराठी", englishName: "Marathi" },
  { code: "pa", name: "ਪੰਜਾਬੀ", englishName: "Punjabi" },
];
`;

fs.writeFileSync('g:/kisan-diary-saas-development/src/lib/translations.ts', output);
console.log("Written successfully");
