const fs = require('fs');

function fix(path) {
  if (fs.existsSync(path)) {
    let content = fs.readFileSync(path, 'utf8');
    // Remove the duplicated block generated by the previous script
    content = content.replace('import { t } from "@/lib/translations";\nimport type { TranslationKey } from "@/lib/translations";\n', '');
    content = content.replace('// from "@/context/AppContext";', '');
    fs.writeFileSync(path, content);
    console.log('Fixed imports in', path);
  }
}

fix('g:/kisan-diary-saas-development/src/app/app/khata/page.tsx');
fix('g:/kisan-diary-saas-development/src/app/app/settings/page.tsx');
